version: '3.8'

services: 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ../:/var/www/html
    ports:
      - "80:80"
      - "9003:9003"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "80:80"
      - "9004:9003"
      # Changed host port to 9004
    user: vscode
    command: sleep infinity

volumes:
  mariadb-data:
