version: '3.8'

services: 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ..:/var/www/html
    ports:
      - "8080:80"
      - "9003:9003"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

volumes:
  mariadb-data:
